site_name: Estudos para Concursos

theme:
  name: material
  language: pt-BR

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest

  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Modo escuro

  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Modo claro

nav:
  - Início: index.md
  - Português: portugues.md
  - Informática: informatica.md
  - Constitucional: constitucional.md
  - Direito administrativo: dir.administrativo.md
  - Leis Especiais: leis-especiais.md
  - Raciocínio Lógico: rlm.md
  - Administração Geral: administracao.md