site_name: Estudos para Concursos

theme:
  name: material
  language: pt-BR

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Modo escuro

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Modo claro

nav:
  - Início: index.md
  - Português: portugues.md
  - Informática: informatica.md
  - Direito Constitucional: dir.constitucional.md
  - Direito Administrativo: dir.administrativo.md
  - Raciocínio Lógico: rlm.md
  - Administração Geral: administracao.md

  - Leis Especiais:
   
      - Lei 8429: leis.md/lei-8429.md
      - Lei 9784: leis.md/lei-9784.md
      -Lei 14.133: Leis.md/lei-14133.md
