site_name: Meu Estudo para Concursos

theme:
  name: material
  language: pt-BR

nav:
  - Início: index.md

  - Português:
      - Crase: docs/portugues/crase.md
      - Conjunções: docs/portugues/conjuncoes.md
      - Pronomes: docs/portugues/pronomes.md
      - Verbos: docs/portugues/verbos.md
      - redação: docs/portugues/redacao.md
      - Analise Sintática: docs/portugues/sintatica.md

  - Direito Administrativo:
      - Agentes Públicos: docs/administrativo/agentes-publicos.md
      - Administração Pública: docs/administrativo/administracao.md

  - Informática:
      - Informática Básica: docs/informatica/informatica-basica.md


  - Leis:
      - Lei 8.429/92: docs/leis/lei-8429.md
      - Lei 9.784/99: docs/leis/lei-9784.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
